version: '2'
services:
    playaround-app:
        image: playaround
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://playaround-mysql:3306/playaround?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    playaround-mysql:
        extends:
            file: mysql.yml
            service: playaround-mysql
